### ISSUE TITLE
Others  examples of share images

### ISSUE THREAD

**Issue by andrecoweb** [illuzor/Android-Sharing-Extension-ANE#4]
Hello, 

Is posible more examples  of share images.

I have an image .PNG in my project but no work.

**Comment by illuzor** [comment]
You must just call 
```
SharingExtension.shareImage(file, "Choser title", "Message"));
```

Be shure your file is exists.
And don`t forget add premissions to manifest:
```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

**Comment by andrecoweb** [comment]
Hello!, 

This work for me 


[Embed(source='../../image_for_share.jpg')] private var yourImageClass:Class;

var yourImage:Bitmap = new yourImageClass();
var fileData:BitmapData = yourImage.bitmapData;

var jpgEncoder:JPGEncoder = new JPGEncoder( 90 );
var btArray:ByteArray = jpgEncoder.encode( fileData );
				
var file:File = File.documentsDirectory.resolvePath("image_for_share.jpg");
				
var stream:FileStream = new FileStream(); // write file to local memory
stream.open(file, FileMode.WRITE);
stream.writeBytes(btArray);
stream.close();

SharingExtension.shareImage(file,'Compartir Zia&Zio','Entra ahora a http://zia-zio.com');

**Comment by illuzor** [comment]
nice
