### ISSUE TITLE
AIR 22 compatibility

### ISSUE THREAD

**Issue by basalicante** [illuzor/Android-Sharing-Extension-ANE#5]
Doesn't seem to be working with AIR 22 anymore.

`Error: The extension com.illuzor.extensions.SharingExtension has either a namespace version or library.swf with a version that is incompatible with the applications namespace or root SWF.`

Got plans for updating this great little ANE? Thanks, either way ;-)

**Comment by illuzor** [comment]
No problem. But I'm not sure whether it will work correctly. AIR 22 contains really many bugs.

I think your problem with swf version of your main .swf file. Update it to 32+

**Comment by basalicante** [comment]
You're right! Hadn't updated my IDE on my laptop and the version was behind. Duh! Thanks!
