### ISSUE TITLE
Samsung Tab4 not working :(

### ISSUE THREAD

**Issue by Gamezpedia** [illuzor/Android-Sharing-Extension-ANE#6]

**Comment by illuzor** [comment]
Hello.
"Not working" - is not correct description of problem.
Any logs from debugger and adb?

**Comment by Gamezpedia** [comment]
Hi,
i integrated it in my project and it is not showing any traces, it just quits the application. i tried it adding it to starting of the project to make sure nothing is breaking it, but it just quits the app and i can't find any reason why , i am making an image sharing application but this seems to not working for me :(.

what i already checked :
- It is embedded properly in the swf publish settings i can see it in the publish window .
- i added all the permissions .
- i properly imported it .
- SharingExtension.shareText("Title", "Text for sharing"); << and it just quits whenever it reaches here.

is there any way i can check it what is breaking it ?

please ignore my English grammar i am not a native speaker :)

thanks

**Comment by illuzor** [comment]
You can try to check with adb.
Download android sdk. And run monitor.bat in **tools** folder. Select your device and application in search field.

**Comment by Gamezpedia** [comment]
I Found the problem within my code; 

i commented these lines and it works now,  something was conflicting i don't know what , i also tried to open monitor.bat but there was another issue popping up probably my windows sucks. well anyways this was the cause :) 

if(Capabilities.cpuArchitecture == "ARM")
			{
				NativeApplication.nativeApplication.addEventListener(Event.ACTIVATE, handleActivate, false, 0, true);
				NativeApplication.nativeApplication.addEventListener(Event.DEACTIVATE, handleDeactivate, false, 0, true);
				NativeApplication.nativeApplication.addEventListener(KeyboardEvent.KEY_DOWN, handleKeys, false, 0, true);
			}`

Note: i tried Adobe DataShare native extension too and the same problem. i hope someone will find this info useful.

thanks for the extension it saves allot of time.
